
version: '3'

services:
  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: '*'
        DJANGO_SECRET_KEY: '*'
        DJANGO_CORS_ORIGIN_WHITELIST: '*'
    command: gunicorn config.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
  frontend:
    container_name: front
    build: frontend
    ports:
      - "80:80"
    depends_on:
      - backend